### This workflow will generate documentation to update the GitHub Wiki accordingly.

name: publish-docs

on: # TODO: Have this run on new releases.
  repository_dispatch:
    types: publish-docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-markdown-builder

      - name: Generate documentation
        run: |
          python -m sphinx.cmd.build -b markdown docs docs/_build
          echo 1
          ls docs/_build/_api/
          echo 2
          ls docs/_build/
          echo 3
          ls docs/images/
          echo 4
          mv docs/_build/_api/* docs/_build/
          ls docs/_build/
          echo 5
          mv docs/images/* docs/_build/
          ls docs/_build/

      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: docs/_build
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
